### ISSUE TITLE
Are you alive ?

### ISSUE THREAD

**Issue by rubenh2905** [GravelCZ/FarmBot#5]
Are you alive ?
Are you still not interested to complete this project ?

**Comment by GravelCZ** [comment]
Yes, I am still alive.
But this project is out of date, not completed by a long shot and I don't think it is worth completing now because other projects have already done the same thing even better. For example [Baritone](https://github.com/cabaletta/baritone)

**Comment by rubenh2905** [comment]
But that is just a pathfinder bot, but your project is a cmd, non gui, custom client.

**Comment by nothub** [comment]
maybe you could add a permissive license that allows ruben to complete the project

**Comment by rubenh2905** [comment]
I'm was try to do some thing with mcprotocollib but it was so much harder than i thought, like handling world, physics, movement, etc.
I'm not senior developer, I'm trying extend my knowledge.
I'm was interested to compile it and run it to see how it works.
Is there any alternative completed projects with mcprotocollib ( based on versions 1.8 and 1.12 ) ?
